# we need to specify every crates because of https://github.com/rust-lang/rust-clippy/issues/9555
[jobs.bacon-ls]
command = [
  "cargo", "clippy",
  "-p", "dawncore-apigen",
  "-p", "dawncore-spec",
  "-p", "dawncore-util",
  "-p", "dawncore-cli",
  "--all-targets", "--all-features",
  "--message-format", "json-diagnostic-rendered-ansi",
]
analyzer = "cargo_json"
need_stdout = true

[jobs.bacon-ls.env]
CARGO_TARGET_DIR="./target/bacon-ls/"

[exports.cargo-json-spans]
auto = true
exporter = "analyzer"
line_format = """\
  {diagnostic.level}|:|{span.file_name}|:|{span.line_start}|:|{span.line_end}|:|\
  {span.column_start}|:|{span.column_end}|:|{diagnostic.message}|:|{diagnostic.rendered}|:|\
  {span.suggested_replacement}\
"""
path = ".bacon-locations"
