[package]
name = "dawncore"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest.workspace = true
base64.workspace = true
serde.workspace = true
convert_case = "0"

[[example]]
name = "stream"

[workspace]
members = [".", "cli", "apigen", "generated"]

[workspace.dependencies]
dawncore = { path = "./" }
dawncore-apigen = { path = "./apigen/" }
dawncore-cli = { path = "./cli/" }
dawncore-generated = { path = "./generated/" }
reqwest = { version = "0", features=["json"] }
serde = "1"
serde_json = "1"
toml = "0"
base64 = "0"
tokio = { version = "1", features = ["full"] }
pingora = { version = "0.6", features = ["proxy"] }
clap = { version = "4", features = ["derive"] }
async-trait = "0.1"
sysinfo = "0"
regex = "1"
itertools = "0"
chrono = "0"
