[package]
name = "lapi-apigen"
version = "0.1.0"
edition = "2024"
description = "API extractor and codegen"

[dependencies]
lapi.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
quote = "1"
prettyplease = "0"
syn = "2"
proc-macro2 = "1"
