use std::{fs::File, io::Write, path::Path};

use dawncore::league::{Build, Category, FunctionSpec, TypeReference, TypeSpec, TypeSpecDetail};
use itertools::Itertools;
use proc_macro2::{Span, TokenStream};
use quote::quote;
use syn::Ident;

use crate::league::Resolved;

fn generated_header_comment(build: &Build) -> String {
    let time = chrono::Utc::now();
    let time = format!("{time}");
    let branch = build.branch.as_str();
    let version = build.version.as_str();

    format!(
        r"// -----------------------------------------------------------------------------
// This file was automatically generated by dawncore-apigen.
// DO NOT EDIT MANUALLY.
//
// Generated At: {time}
// Branch: {branch}
// Version: {version}
//
// -----------------------------------------------------------------------------

"
    )
}

pub fn write_types(directory: &Path, resolved: &Resolved) {
    let types = resolved.types.values().collect::<Vec<_>>();

    let header_comment = generated_header_comment(&resolved.build);
    let base = quote! {
        #[allow(unused_imports)]
        use super::*;
        use serde::{Serialize, Deserialize};
    };

    let mut modules = vec![];
    let chunks = types.iter().into_group_map_by(|v| v.category());

    for (category, mut types) in chunks {
        types.sort_by_key(|v| match &v.detail {
            TypeSpecDetail::Object { .. } => 0,
            TypeSpecDetail::Enum { .. } => 1,
            TypeSpecDetail::Unit => 2,
        });

        let module_name = category_to_module_name("types", &category);
        let file = directory.join(format!("{module_name}.rs"));
        modules.push(module_name);

        let mut base = base.clone();
        for spec in types {
            let def = type_as_token_stream(spec);
            base.extend(def);
        }

        let parsed = syn::parse_file(base.to_string().as_str()).unwrap();
        let formatted = prettyplease::unparse(&parsed);

        let mut file = File::create(file).unwrap();
        file.write_all(header_comment.as_bytes()).unwrap();
        file.write_all(formatted.as_bytes()).unwrap();
    }

    let mod_file = directory.join("mod.rs");
    let mut mod_file = File::create(mod_file).unwrap();

    let mod_uses = modules
        .iter()
        .sorted()
        .map(|v| {
            let ident = Ident::new(v.as_str(), Span::call_site());
            quote! {
                mod #ident;
                pub use #ident::*;
            }
        })
        .collect::<Vec<_>>();

    let mod_content = quote! {
        #(#mod_uses)*
    };

    let parsed = syn::parse_file(mod_content.to_string().as_str()).unwrap();
    let formatted = prettyplease::unparse(&parsed);

    mod_file.write_all(header_comment.as_bytes()).unwrap();
    mod_file.write_all(formatted.as_bytes()).unwrap();
}

pub fn write_functions(directory: &Path, resolved: &Resolved) {
    let functions = resolved.functions.values().collect::<Vec<_>>();

    let header_comment = generated_header_comment(&resolved.build);
    let base = quote! {
        #[allow(unused_imports)]
        use crate::types::*;
        use crate::AuthenticatedHttp as __AuthenticatedHttp;
    };

    let mut modules = vec![];
    let chunks = functions.iter().into_group_map_by(|v| v.category());

    for (category, functions) in chunks.iter() {
        let module_name = category_to_module_name("rest", category);
        let file = directory.join(format!("{module_name}.rs"));
        modules.push(module_name);

        let mut base = base.clone();
        for function in functions {
            let def = function_as_token_stream(resolved, function);
            base.extend(def);
        }

        let parsed = syn::parse_file(base.to_string().as_str()).unwrap();
        let formatted = prettyplease::unparse(&parsed);

        let mut file = File::create(file).unwrap();
        file.write_all(header_comment.as_bytes()).unwrap();
        file.write_all(formatted.as_bytes()).unwrap();
    }

    let mod_file = directory.join("mod.rs");
    let mut mod_file = File::create(mod_file).unwrap();

    let mod_uses = modules
        .iter()
        .sorted()
        .map(|v| {
            let ident = Ident::new(v.as_str(), Span::call_site());
            quote! {
                pub mod #ident;
            }
        })
        .collect::<Vec<_>>();

    let mod_content = quote! {
        #(#mod_uses)*
    };

    let parsed = syn::parse_file(mod_content.to_string().as_str()).unwrap();
    let formatted = prettyplease::unparse(&parsed);

    mod_file.write_all(header_comment.as_bytes()).unwrap();
    mod_file.write_all(formatted.as_bytes()).unwrap();
}

pub fn type_as_token_stream(spec: &TypeSpec) -> TokenStream {
    let ident = spec.identifier();
    let ident = Ident::new(ident.as_str(), Span::call_site());

    match &spec.detail {
        TypeSpecDetail::Object { fields } => {
            let field_defs = fields
                .iter()
                .map(|v| {
                    let serial_name = v.name.as_str();
                    let ident = v.ident();
                    let name = Ident::new(ident.as_str(), Span::call_site());
                    let ty = type_path_to_type(v.ty.to_rust_type(false), v.optional);

                    let attr_serde_rename = if ident.as_str() == serial_name {
                        None
                    } else {
                        Some(quote! {
                            #[serde(rename = #serial_name)]
                        })
                    };

                    quote! {
                        #attr_serde_rename
                        pub #name: #ty,
                    }
                })
                .collect::<Vec<_>>();

            quote! {
                #[derive(Debug, Clone, Serialize, Deserialize)]
                pub struct #ident {
                    #(#field_defs)*
                }
            }
        }
        TypeSpecDetail::Enum { entries } => {
            let mut entries = entries.clone();
            entries.sort_by_key(|v| v.value);

            let entry_defs = entries
                .iter()
                .map(|v| {
                    let serial_name = v.name.as_str();
                    let name = Ident::new(v.ident().as_str(), Span::call_site());
                    let value = v.value as isize;

                    quote! {
                        #[serde(rename = #serial_name)]
                        #name = #value,
                    }
                })
                .collect::<Vec<_>>();

            let name_match_arms = entries
                .iter()
                .map(|v| {
                    let ident = Ident::new(v.ident().as_str(), Span::call_site());
                    let name = v.name.as_str();

                    quote! {
                        Self::#ident => #name,
                    }
                })
                .collect::<Vec<_>>();

            quote! {
                #[derive(Debug, Clone, Serialize, Deserialize)]
                pub enum #ident {
                    #(#entry_defs)*
                }

                impl #ident {
                    pub fn name(&self) -> &'static str {
                        match self {
                            #(#name_match_arms)*
                        }
                    }
                }
            }
        }
        TypeSpecDetail::Unit => {
            quote! {
                #[derive(Debug, Clone, Serialize, Deserialize)]
                pub struct #ident;
            }
        }
    }
}

pub fn function_as_token_stream(resolved: &Resolved, function: &FunctionSpec) -> TokenStream {
    let arg_defs = function
        .arguments
        .iter()
        .map(|v| {
            let name = Ident::new(v.ident().as_str(), Span::call_site());
            let ty = type_path_to_type(v.ty.to_rust_type(false), v.optional);

            quote! {
                #name: #ty
            }
        })
        .collect::<Vec<_>>();
    let ident = Ident::new(function.ident().as_str(), Span::call_site());
    let returns_path = match &function.returns {
        Some(returns) => returns.to_rust_type(false),
        None => "()".to_owned(),
    };
    let returns = type_path_to_type(returns_path, false);

    let parameters = function
        .arguments
        .iter()
        .filter(|v| v.parameter)
        .collect::<Vec<_>>();
    let queries = function
        .arguments
        .iter()
        .filter(|v| v.query)
        .collect::<Vec<_>>();
    let url_def = {
        let url = if !parameters.is_empty() {
            let mut url = function.url.clone();
            for parameter in parameters.iter() {
                let interpolated = format!("{{{}}}", parameter.ident());
                url = url
                    .replace(
                        format!("{{{}}}", parameter.name).as_str(),
                        interpolated.as_str(),
                    )
                    .replace(
                        format!("{{+{}}}", parameter.name).as_str(),
                        interpolated.as_str(),
                    );
            }

            let format_arg_defs = parameters
                .iter()
                .map(|v| {
                    let ident = Ident::new(v.ident().as_str(), Span::call_site());
                    let value = match &v.ty {
                        TypeReference::Reference(name) => {
                            match resolved.types.get(name).unwrap().detail {
                                TypeSpecDetail::Enum { .. } => {
                                    quote! {
                                        #ident.name()
                                    }
                                }
                                _ => quote! { #ident },
                            }
                        }
                        _ => quote! { #ident },
                    };

                    if v.optional {
                        quote! {
                            #ident = match #ident {
                                Some(#ident) => format!("{}", #value),
                                None => String::new()
                            }
                        }
                    } else {
                        quote! {
                            #ident = #value
                        }
                    }
                })
                .collect::<Vec<_>>();

            quote! {
                format!(#url, #(#format_arg_defs),*)
            }
        } else {
            let url = function.url.as_str();

            quote! {
                std::string::String::from(#url)
            }
        };

        let query_applies = queries
            .iter()
            .map(|v| {
                let ident = Ident::new(v.ident().as_str(), Span::call_site());
                let format = format!("{}={{}}", v.name);
                let value = type_reference_to_url_parameter(resolved, &v.ty, &ident);

                if v.optional {
                    quote! {
                        if let Some(#ident) = &#ident {
                            let _value = #value;
                            url.push_str(format!(#format, _value).as_str());
                        }
                    }
                } else {
                    quote! {
                        {
                            let _value = #value;
                            url.push_str(format!(#format, _value).as_str());
                        }
                    }
                }
            })
            .collect::<Vec<_>>();

        quote! {
            let url = {
                let mut url = #url;
                #(#query_applies)*

                url
            };
        }
    };

    let builder_def = {
        let value = match function.method {
            dawncore::league::FunctionMethod::Get => {
                quote! { client.get(client.host.join(url.as_str()).unwrap()) }
            }
            dawncore::league::FunctionMethod::Post => {
                quote! { client.post(client.host.join(url.as_str()).unwrap()) }
            }
            dawncore::league::FunctionMethod::Put => {
                quote! { client.put(client.host.join(url.as_str()).unwrap()) }
            }
            dawncore::league::FunctionMethod::Patch => {
                quote! { client.patch(client.host.join(url.as_str()).unwrap()) }
            }
            dawncore::league::FunctionMethod::Delete => {
                quote! { client.delete(client.host.join(url.as_str()).unwrap()) }
            }
        };

        quote! {
            let mut builder = #value;
        }
    };

    let builder_set_body = {
        let pairs = function
            .arguments
            .iter()
            .filter(|v| !v.parameter)
            .map(|v| {
                let ident = v.ident();
                let name = v.name.as_str();
                let value = syn::parse_str::<syn::Ident>(ident.as_str()).unwrap();

                quote! { #name: #value }
            })
            .collect::<Vec<_>>();

        let json = quote! {
            serde_json::json!({
                #(#pairs),*
            })
        };

        quote! {
            builder = builder.json(&{ #json });
        }
    };

    let response_def = {
        quote! {
            let response = builder.send().await?;
        }
    };

    let return_statement = {
        if function.returns.is_some() {
            quote! {
                response.json().await
            }
        } else {
            quote! {
                Ok(())
            }
        }
    };

    quote! {
        pub async fn #ident(client: __AuthenticatedHttp, #(#arg_defs),*) -> reqwest::Result<#returns> {
            #url_def
            #builder_def
            #builder_set_body
            #response_def
            #return_statement
        }
    }
}

fn category_to_module_name(prefix: &str, category: &Category) -> String {
    match category {
        Category::Uncategorized => String::from(prefix),
        _ => format!("{prefix}_{category}"),
    }
}

fn type_path_to_type(path: String, optional: bool) -> syn::Type {
    let path = if optional {
        format!("std::option::Option<{}>", path)
    } else {
        path
    };

    syn::parse_str::<syn::Type>(path.as_str()).unwrap()
}

fn type_reference_to_url_parameter(
    resolved: &Resolved,
    reference: &TypeReference,
    ident: &Ident,
) -> TokenStream {
    match reference {
        TypeReference::Vector(ty) => {
            let inner = type_reference_to_url_parameter(
                resolved,
                ty.as_ref(),
                &Ident::new("value", Span::call_site()),
            );
            quote! {
                #ident.iter().map(|value| {
                    format!("{}", #inner)
                }).collect::<Vec<_>>().join(",");
            }
        }
        TypeReference::Reference(name) => match resolved.types.get(name).unwrap().detail {
            TypeSpecDetail::Enum { .. } => {
                quote! {
                    #ident.name()
                }
            }
            TypeSpecDetail::Object { .. } => {
                quote! {
                    serde_json::to_string(&#ident).unwrap()
                }
            }
            _ => quote! { &#ident },
        },
        _ => quote! { &#ident },
    }
}
